// Shared ESLint config for framework-agnostic packages.
// apps/web has its own config generated by the @nuxt/eslint module.
import { createConfigForNuxt } from '@nuxt/eslint-config/flat'

export default createConfigForNuxt({
  features: {
    stylistic: true,
  },
})
